Get albums list
wolox-training/shm-express-js pull request #13
Opened 2019-07-19 20:15 UTC by shernanm

## Summary

* The endpoint is implemented that allows you to list the purchased albums.
* Their respective tests are carried out.
* Mocks are made for the response of the external service.

## Trello Card

https://trello.com/c/Bh9Ao9Yw

2019-07-22 16:57 UTC, raparicio6 requested changes

2019-07-22 16:57 UTC, raparicio6 commented on app/controllers/album.js
> +  return findAllAlbums(req.params.user_id)
we always use camel case

2019-07-22 16:57 UTC, raparicio6 commented on app/controllers/album.js
> +    .then(albums => {
remove { }

2019-07-22 16:57 UTC, raparicio6 commented on test/album.test.js
> +albumMock();
you should put this somewhere, for example in a before each

2019-07-29 18:41 UTC, molinajulian requested changes

2019-07-29 18:41 UTC, molinajulian commented on app/controllers/album.js
> +  return findAllAlbums(req.params.userId)
Use findAllBy . Is more scalable

2019-07-29 18:41 UTC, molinajulian commented on package.json
> +    "nock": "^10.0.6",
Nock is dev-dependency. Also, delete this because you are use jest

2019-07-29 19:08 UTC, molinajulian approved these changes

2019-07-29 19:10 UTC, merged