Disable all sessions
wolox-training/shm-express-js pull request #15
Opened 2019-07-19 23:29 UTC by shernanm

## Summary

* The endpoint is implemented to disable all active sessions for a specific user.
* Their respective tests are carried out.

## Trello Card

https://trello.com/c/wrMZDcQQ

2019-07-31 17:23 UTC, raparicio6 requested changes

2019-07-31 17:23 UTC, raparicio6 commented on app/controllers/user.js
> +      res.status(200).send({ message: 'All sessions have been disabled' });
you are missing the return. also, sending status 200 is by default in Express

2019-08-01 20:45 UTC, molinajulian requested changes

2019-08-01 20:45 UTC, molinajulian commented on app/middlewares/session.js
> +        findUserBy({ email }, ['allowedDate']).then(({ allowedDate }) => {
return here

2019-08-01 20:45 UTC, molinajulian commented on app/middlewares/session.js
> +          const dateToken = new Date(iat * 1000);
Date? check `moment` library

2019-08-01 20:45 UTC, molinajulian commented on app/models/user.js
> +        defaultValue: Date.now()
This value `Date.now()` its constant. Check how to use literal function for save, for example `NOW()` or `SYSDATE()`

2019-08-01 20:45 UTC, molinajulian commented on migrations/migrations/20190801172008-allowed-date-column.js
> +      type: Sequelize.DATE
Add here `defaultValue` and `allowNull:false`

2019-08-02 13:05 UTC, molinajulian requested changes

2019-08-02 13:05 UTC, molinajulian commented on app/controllers/user.js
> +  findUserBy({
Return here

2019-08-02 13:05 UTC, molinajulian commented on app/middlewares/session.js
> +          const dateToken = moment.unix(iat);
Is more easy ; moment(allowedDate), moment(iat) and moment.diff(moment1,moment2)

2019-08-05 15:00 UTC, raparicio6 approved these changes

2019-08-05 15:01 UTC, raparicio6 commented
Excellent work

2019-08-05 15:02 UTC, merged