Tests documentation
wolox-training/shm-express-js pull request #6
Opened 2019-06-17 17:58 UTC by shernanm

## Summary

* The tests, and their respective documentation for the endpoint users, were implemented, taking into account the following cases:

  * Test when the creation of a user is satisfactory.
  * Test when the creation of a user fails to use an email that is in use.
  * Test when the creation of a user fails because the password does not meet the conditions.
  * Test when the creation of a user fails by not sending a mandatory parameter.

## Trello Card

https://trello.com/c/0VzDUC4G

2019-06-18 03:16 UTC, raparicio6 commented
Update with master

2019-06-18 15:55 UTC, raparicio6 approved these changes

2019-06-18 18:18 UTC, molinajulian requested changes

2019-06-18 18:18 UTC, molinajulian commented on test/users.test.js
> +  test('Successful test when registering user', () =>
Replace `()` for `done` in all test.

2019-06-18 18:18 UTC, molinajulian commented on test/users.test.js
> +        expect(response.statusCode).toBe(201);
Search user in db and check fields.

2019-06-18 18:18 UTC, molinajulian commented on test/users.test.js
> +        return dictum.chai(response, 'Successful test creating user');
This is unnecessary. In each test, you must call `done()` in the last line test. Also add `dictum.chai(response)` for only one successful case.
Check in all test and refactor this.

2019-06-18 18:18 UTC, molinajulian commented on test/users.test.js
> +            expect(response.statusCode).toBe(503);
This is wrong. You must be return `400 BAD REQUEST` when the request contain an email exist. Change whatever is needed for that.

2019-06-18 18:18 UTC, molinajulian commented on test/users.test.js
> +            expect(response.statusCode).toBe(503);
Also check the message for error

2019-06-18 18:18 UTC, molinajulian commented on documentation.js
> +const dictum = require('dictum.js');
This file is unnecessary. When you call `dictum.chai(response)` the file with documentation is created automatically.

2019-06-18 18:18 UTC, molinajulian commented on test/users.test.js
> +        expect(response.statusCode).toBe(503);
This is a 400 bad request, no 503. 503 is bad gateway, and representing when the server is down.

2019-06-18 21:10 UTC, molinajulian requested changes

2019-06-18 21:10 UTC, molinajulian commented on test/users.test.js
> +        }).then(userDb => {
You can deconstruct here too :+1: . `({firstName,lastName,email})` instead of `userDb`

2019-06-19 15:51 UTC, raparicio6 approved these changes

2019-06-19 16:07 UTC, molinajulian approved these changes

2019-06-19 16:10 UTC, merged