Middlewares
wolox-training/shm-express-js pull request #7
Opened 2019-06-19 21:02 UTC by shernanm

## Summary

* The use of middleware is implemented in the endpoints of users and albums.

## Trello Card

https://trello.com/c/3JYipc49

2019-06-20 02:20 UTC, raparicio6 requested changes

2019-06-20 02:20 UTC, raparicio6 commented on app/controllers/album.js
> +// const errors = require('../errors');
dont leave comments

2019-06-20 02:20 UTC, raparicio6 commented on app/controllers/user.js
> +        message: `User has been created successfully with ID ${response.id}`
Why do you send a message in the response? You dont do this in APIs Rest, you just send the data with a status code

2019-06-20 02:20 UTC, raparicio6 commented on app/schemas/user.js
> +const { User } = require('../models');
great work!

2019-06-20 02:20 UTC, raparicio6 commented on app/util.js
> +    .hash(user.password, 10)
dont harcode this

2019-06-24 12:15 UTC, molinajulian requested changes

2019-06-24 12:15 UTC, molinajulian commented on app/controllers/user.js
> +  const user = req.body;
You can deconstruct this in req . `({ body }, res, next)`

2019-06-24 12:15 UTC, molinajulian commented on app/middlewares/checkSchema.js
> +  return errors.isEmpty() ? next() : res.status(400).json({ errors: errors.array(), ...error.badRequest() });
You don't need set status. Check `errors.js` and add key `BAD_REQUEST` with status code `400`. Also, `json` is not necessary.  If you want send a json, is more easy, use `.send({ key: value})`.

2019-06-24 12:15 UTC, molinajulian commented on app/util.js
> +      throw errors.encryptionError();
Perfect!

2019-06-24 12:15 UTC, molinajulian commented on test/users.test.js
> +              message: 'Invalid request parameters',
This is not the same with what we talked about. You must be send an array for errors in message :( . Check this in all test

2019-06-25 20:16 UTC, raparicio6 requested changes

2019-06-25 20:16 UTC, raparicio6 commented on app/controllers/user.js
> +exports.createUser = ({ body }, res, next) =>
for convention we always put `req` here

2019-06-25 20:22 UTC, shernanm commented on app/controllers/user.js
> +exports.createUser = ({ body }, res, next) =>
I did it at the suggestion of Moli

2019-06-25 20:26 UTC, raparicio6 commented on app/controllers/user.js
> +exports.createUser = ({ body }, res, next) =>
ok its fine in that case

2019-06-28 17:55 UTC, molinajulian approved these changes

2019-06-28 18:29 UTC, raparicio6 approved these changes

2019-06-28 19:57 UTC, merged