User sign in
wolox-training/shm-express-js pull request #8
Opened 2019-06-28 20:56 UTC by shernanm

## Summary

* The login was implemented.
* Authentication by means of token was implemented.

## Trello Card

https://trello.com/c/XN5atBMq

2019-07-01 12:51 UTC, molinajulian requested changes

2019-07-01 12:51 UTC, molinajulian commented on app/controllers/user.js
>  const validations = require('../util');
Rename for `utils`. Remember, you must be declarative. Also, the file must be `utils.js`

2019-07-01 12:51 UTC, molinajulian commented on app/errors.js
> +  internalError('Error trying to generate the token.', exports.GENERATE_TOKEN_ERROR);
Move internal codes to top, and methods for bottom or on the contrary :+1: . This form is more organized.

2019-07-01 12:51 UTC, molinajulian commented on app/controllers/user.js
> +    .then(foundUser => {
This works but I think that you can improve this. Specially, the part when you return null. What should happen if user does not exist?

2019-07-01 12:51 UTC, molinajulian commented on app/controllers/user.js
> +          .passwordDecryption(password, foundUser.password)
It is not bad that you save this method in utils, but you should know that you can create a service for `jwt`. Check the advantages and disadvantages of these two options and then we talk

2019-07-01 12:51 UTC, molinajulian commented on app/services/users.js
> +exports.findUser = email =>
Maybe create `findUserBy` and you pass options. Its more scalable

2019-07-01 12:51 UTC, molinajulian commented on app/util.js
> +    .catch(() => {
You can do `.catch(errors.encryptionError)`. You pass implicitly the parameters received by catch and return the function. Its similar to do `.catch(err => errors.encryptionError(err))`.

2019-07-01 12:51 UTC, molinajulian commented on test/users.test.js
> +  test('Successful test when sign in', () =>
Add more cases

2019-07-01 12:51 UTC, molinajulian commented on test/users.test.js
> +            jwt.verifyAsync(userSignIn.body.token, config.seed).then(token => ({
Maybe create a function to check token in tests?

2019-07-01 12:51 UTC, molinajulian commented on test/users.test.js
> +      .send({
Maybe create a const for this object

2019-07-01 14:29 UTC, raparicio6 commented on .travis.yml
> +  - CXX=g++-4.8 NODE_ENV=testing SEED=wolox-training
where it is defined this seed you are using?

2019-07-04 16:21 UTC, molinajulian approved these changes

2019-07-04 16:21 UTC, molinajulian commented on app/services/users.js
> +    raw: true,
Why ?

2019-07-04 18:47 UTC, raparicio6 approved these changes

2019-07-04 18:57 UTC, merged