Get user list
wolox-training/shm-express-js pull request #9
Opened 2019-07-04 19:28 UTC by shernanm

## Summary

* An endpoint is implemented that allows to list all the users that have registered and only authenticated users can access this data.

## Trello Card

https://trello.com/c/svlrGKj9

2019-07-04 19:54 UTC, raparicio6 requested changes

2019-07-04 19:54 UTC, raparicio6 commented on app/controllers/user.js
> +  logger.info('getUserList method start.');
Log the req data for example the query

2019-07-04 19:54 UTC, raparicio6 commented on app/controllers/user.js
> +    .then(foundUsers => utils.mapperUserList(foundUsers, limit, page))
Import mapper method with destructuring

2019-07-04 19:54 UTC, raparicio6 commented on app/controllers/user.js
> +    .findAllUser(limit, offset)
All users

2019-07-04 19:54 UTC, raparicio6 commented on app/controllers/user.js
> +    .then(response => res.status(200).send(response))
You dont need to set the 200. It is set by default

2019-07-04 19:54 UTC, raparicio6 commented on app/services/users.js
> +    throw errors.databaseError(`${err}`);
If err is a string you dont need to put the ‘ and ${}

2019-07-04 19:54 UTC, raparicio6 commented on app/utils.js
> +exports.mapperUserList = (usersData, limit, page) => {
Use destructuring when receiving usersData parameter

2019-07-10 17:26 UTC, raparicio6 requested changes

2019-07-10 17:26 UTC, raparicio6 commented on app/controllers/user.js
> +  logger.info(`CreateUser method start, request methods: ${req.method}, endpoint: ${req.path}.`);
always log body (if it is a post) and headers

2019-07-10 17:26 UTC, raparicio6 commented on app/middlewares/session.js
> +      .catch(error => {
remove unnecesary { }

2019-07-11 02:06 UTC, raparicio6 approved these changes

2019-07-12 12:39 UTC, molinajulian approved these changes

2019-07-12 15:14 UTC, merged